language: node_js
node_js:
  - "10"
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
sudo: required

before_install:
  - mysql -u root < packages/db-archivist-sql/resources/schema.sql
install: 
  - yarn install
  - yarn build
